### ISSUE TITLE
Background content blocked by buttons

### ISSUE THREAD

**Issue by OricTosh** [OSAlt/geek-beacon-site#20]
The title Geek Beacon, your guilding light to all things geek. Is blocked by the Buttons at the top.
Here is a full size screen dump, asked for feeeback from @ExillustX from 
https://github.com/OSAlt/geek-beacon-site/pull/19
![layout](https://user-images.githubusercontent.com/1838646/28201984-3b3087e6-686b-11e7-906b-40ad922edbcf.png)
Just needs the back image to come down a bit, it's the same upon main site http://geekbeacon.org/

**Comment by safaci2000** [comment]
There's no way around that.. you resolution is too small for the landing page.  Short of re-creating a different set of icons to support every possible variation.. I don't think there is an easy fix. 

Again..this is a temporary landing page.. not meant to be the a full mobile and responsive design presence.  I don't mind polishing it up...but I really don't think its worth the time/effort to re-create graphics in all possible variation to support every possible for factor.

**Comment by OricTosh** [comment]
Is not the geek beacon...  just an image? So could be made to have more room at the top to allow for the buttons in the foreground. Don't get that you need extra sets of buttons.
When you get content in the middle, the foreground scrolls and you can see the blocked text which is a static image. That image I posted is how I see it upon a 19" inch screen. 
@safaci2000 How does it look to you? 
As I can't belive that the current page looks good enough for release.

**Comment by safaci2000** [comment]
If you move it down you mess up the view for larger displays.  It's a slipper slope.  Like I said.. it's a place holder.   If it mostly works, i'm not too concerned about this, but happy to take patches if it bothers you to that extent.

The smaller buttons comment was to have smaller buttons on smaller displays and dynamically change the icon set based on resolution.

**Comment by ExillustX** [comment]
hey, i can fix this issue by using media queries... later i will make some changes for this issue.

**Comment by sahasayan** [comment]
#### pull request #21 has a fix for this issue.

![gb](https://user-images.githubusercontent.com/14250910/28241917-42360a3c-69bc-11e7-881b-45ef3f421bc8.png)

**Comment by safaci2000** [comment]
Sorry that's a no go.  I'm pretty sure that won't pass any level of scrutiny.  The front page needs to have the Words and photo below.  If need be you can move the wallpaper a bit lower, but having the icons in the middle of the screen won't work.

**Comment by OricTosh** [comment]
![good_layout](https://user-images.githubusercontent.com/1838646/28498664-3c296812-6f9a-11e7-8c2b-fceb4c10e755.png)
Looking at the current page upon the geek beacon site. I would say that the background content is no longer blocked, Well done on a good job. I'm also closing this issue
