### ISSUE TITLE
Contact/ Credit Page

### ISSUE THREAD

**Issue by safaci2000** [OSAlt/geek-beacon-site#35]
Publish and update the contact page.  Link it off the main site. (via menu admin? ) 

Depends on:  Arts assets from m-bot.  

TODO: determine who is on the credit page, etc... grouping? tagging in contact page.

need: social media / other links for all parties..

**Comment by nixiepixel** [comment]
For early phases, I really like the idea of having all the core group Beacon Builders on here. Those in our GB Leaders group, plus M-bot (for all his creative contributions) as well as other creatives as they really live and die by having links and references to their social media. (I have 1 video editor + one other animator in that catagory that would be great to add.)

**Comment by safaci2000** [comment]
@nixiepixel we probably should create a document.  I have YOUR social media info..but I don't think i have all the social media links for all the people that contributed.  I was going to reach out to m-bot and get his dets, but if we had a link to say:   Person, contact links ie. twitter, fb, etc, and photo I can crank out a contacts page easily enough based on the existing template.

**Comment by safaci2000** [comment]
Done.
