### ISSUE TITLE
Menu enhancement

### ISSUE THREAD

**Issue by safaci2000** [OSAlt/geek-beacon-site#52]
Allow menu items to replace text with an image. 

Example
Hover over Social 
Being a drop down with two images. 

One for discord another for discourse. 

Both are simply the logo and when clicked then can take you to an external website or another internal page.

**Comment by BigWhale** [comment]
I made a special 'page' type and called it a MenuItem. It has two new properties "external_link" and "menu_icon". 

Basically it serves as a placeholder for menus, but it has no other appearance, you can't display it as a page. So you can create a level 1 menu item with it and it will serve as a drop down menu placeholder, then you can add two more child menu items. There you can pick an external links and menu icons.

Right now icons are cropped to 64x64 and placed in the menu as an inline-block in front of the title. I added all the necessary CSS and template fixes. 

Also, you should merge my other branch before you can merge #54.

**Comment by safaci2000** [comment]
This is no longer an issue.  Closing this out.
