### ISSUE TITLE
Content won't scroll

### ISSUE THREAD

**Issue by OricTosh** [OSAlt/geek-beacon-site#8]
Main content won't scroll
Inner window content will scroll but not the outer main window
my resolution is 1366 x 768

**Comment by ExillustX** [comment]
i pushed pull requests #6 , #7,  with a fix for this issue, and now waiting for the merge.

**Comment by safaci2000** [comment]
Thanks @ExillustX.  Merged the changes in.  @OricTosh Please validate when you have a chance.

**Comment by OricTosh** [comment]
The content scrolls, for inner and outer in the Geeks Aboard page okay now;
When you click the OS-Alt button it opens in a new tab; As does the page for the Squrrial Army. The gaming page wont scroll, so likey to get clipped when viewing on small screens; same with You Tube Page. 
Is there not a gobal scroll for all the pages upon the site?

**Comment by OricTosh** [comment]
Geeks Abroad and Join Us scrolls okay upon a 15 inch laptop screen. The device that I was using in my first comment. The Gaming and the Live on You Tube page won't scroll 
Upon the Join us page, the google form asks you to sign in, though the google user is already signed in.

**Comment by ExillustX** [comment]
@OricTosh is your issue looks solved on the last version [here](http://sayansaha.me/geek-beacon-site/)?

**Comment by OricTosh** [comment]
@ExillustX Looked at the content upon the link you posted. Buttons now fit across the screen, whereas before the join us button was centered under the others. All the content in all the buttons scrolls up and down upon a small screen or as needed. The row of buttons could come down by the half the height of one of them as it's blocking the background image. Attach a file of it 
![blocked_view](https://user-images.githubusercontent.com/1838646/28070092-b147c342-6643-11e7-81c9-fbe7574228f8.png)

Will you be pushing the linked content to the main site? Keep up the good work.

**Comment by safaci2000** [comment]
That patch is out of date.  It needs a rebase and the top button need to be moved up above Geek Beacon in the default desktop view.  If those issues get fixed up happy to merge that in.

**Comment by hollowdoor** [comment]
Hello. I'm new here.

On the http://geekbeacon.org/stream.html page I commented out a line in the browser style editor:

```css
iframe.gaming {
	margin: 0 21.5%;
	display: block;
	border: 3px solid black;
	position: absolute;
	width: 57%;
        /*With the next line commented out there is a scroll bar.*/
	/*height: calc(100% - 316px);*/
	top: 308px;
	
}
```

Suddenly the page is scrollable. Don't know if that's of any help.

**Comment by ExillustX** [comment]
welcome @hollowdoor , thanks for letting us know. however that trick only works on `stream.html` page. but thanks anyway 😄

**Comment by hollowdoor** [comment]
It's also works on the gaming.html page. Those were the only two pages effected from my end.

**Comment by safaci2000** [comment]
I'll push a patch a bit later. Or you can do a pull request and I'll get the patch rolled out.  


_Sent from my OnePlus ONE A2005 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hollowdoor** [comment]
@safaci2000 If you're talking to me I can patch it, but do you think removing the offending CSS is enough?

**Comment by safaci2000** [comment]
@hollowdoor I pushed a test patch on https://osalt.github.io/geek-beacon-site/ can you look it over and see if that works as expect for you?

**Comment by OricTosh** [comment]
Looks like all the content scrolls on all pages. Needs some work to sort out the layout; As the buttons are blocking the text behind
![full_screen_layout](https://user-images.githubusercontent.com/1838646/28155234-b086ac30-67a5-11e7-8e8d-a7672b898154.png)

**Comment by ExillustX** [comment]
@OricTosh @hollowdoor feedback please: #19

**Comment by safaci2000** [comment]
Merged the latest patch from @ExillustX.  Thank you for the fix.  I'll leave this open for a day or so for anyone to chime in then I'll close this out.  Changes have been deployed on geekbeacon.org

**Comment by hollowdoor** [comment]
I'm late to the party. The fix looks good.
